### ISSUE TITLE
Post API missing comments?

### ISSUE THREAD

**Issue by carsenk** [bitclout/backend#67] opened 2021-06-30 20:09 UTC
![image](https://user-images.githubusercontent.com/10162347/124024574-9efe4b80-d9ac-11eb-89fe-5dfa80c92e76.png)

Endpoint: /api/v0/get-single-post

Params Body:

```
{
    "PostHashHex": "001279e0455dc7b35575a0e80ab13a3b4e2be32e3942dc6ec05261b2e5377dac"
}
```

This post for example has a comment, upon return of the post data Comments is showing an empty array [].

**Comment by AdityaChaudhary0005** [comment] 2021-07-02 05:52
Not really :P 

The post right now has 2 comments and so is the length of Comments[]

![Screenshot from 2021-07-02 11-18-30](https://user-images.githubusercontent.com/55331140/124226925-7a7aae80-db27-11eb-883b-db52e3aa240c.png)

**Comment by shrimalmadhur** [comment] 2021-07-09 21:06
I tried to repro it but couldn't. It does work as expected for me. I can even run it on my local and have comments being returned. Might want to close this @diamondhands0 , but I do wonder if the caller doesn't send any (or 0 which is default int) `CommentLimit` should we set a default in the `backend` too? 
By default the `CommentLimit` from the frontend is set to `10` so we are good there. @carsenk - as mentioned by @AdityaChaudhary0005 , you need to set the `CommentLimit` in the request.

**Comment by maebeam** [comment] 2021-07-10 14:58
Closing due to inability to reproduce. Please let me know if this needs to be reopened.

**Closed by maebeam** 2021-07-10 14:58 UTC
